<a href="https://colab.research.google.com/github/Aniket-Kumar-7/Machine-Learning/blob/main/Heart_Attack_Predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn
import warnings
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,r2_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
warnings.filterwarnings('ignore')

In [4]:
data=pd.read_csv(r'/content/heart_attack_prediction_india.csv')

In [5]:
data.shape

(10000, 26)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Patient_ID               10000 non-null  int64
 1   State_Name               10000 non-null  object
 2   Age                      10000 non-null  int64
 3   Gender                   10000 non-null  object
 4   Diabetes                 10000 non-null  int64
 5   Hypertension             10000 non-null  int64
 6   Obesity                  10000 non-null  int64
 7   Smoking                  10000 non-null  int64
 8   Alcohol_Consumption      10000 non-null  int64
 9   Physical_Activity        10000 non-null  int64
 10  Diet_Score               10000 non-null  int64
 11  Cholesterol_Level        10000 non-null  int64
 12  Triglyceride_Level       10000 non-null  int64
 13  LDL_Level                10000 non-null  int64
 14  HDL_Level                10000 non-null  int64
 15  Systolic_BP              10000 non-null  int64
 16  Diastolic_BP             10000 non-null  int64
 17  Air_Pollution_Exposure   10000 non-null  int64
 18  Family_History           10000 non-null  int64
 19  Stress_Level             10000 non-null  int64
 20  Healthcare_Access        10000 non-null  int64
 21  Heart_Attack_History     10000 non-null  int64
 22  Emergency_Response_Time  10000 non-null  int64
 23  Annual_Income            10000 non-null  int64
 24  Health_Insurance         10000 non-null  int64
 25  Heart_Attack_Risk        10000 non-null  int64
dtypes: int64(24), object(2)
memory usage: 2.0+ MB

In [7]:
cols=["Patient_ID", "State_Name", "Emergency_Response_Time", "Heart_Attack_History"]

In [8]:
data.duplicated().sum()

np.int64(0)

In [9]:
data.drop(["Patient_ID", "State_Name", "Emergency_Response_Time", "Heart_Attack_History"],axis=1,inplace=True)

In [10]:
data.head()

,Age,Gender,Diabetes,Hypertension,Obesity,Smoking,Alcohol_Consumption,Physical_Activity,Diet_Score,Cholesterol_Level,...,HDL_Level,Systolic_BP,Diastolic_BP,Air_Pollution_Exposure,Family_History,Stress_Level,Healthcare_Access,Annual_Income,Health_Insurance,Heart_Attack_Risk
0,42,Female,0,0,1,1,0,0,9,248,...,42,93,119,1,0,4,0,611025,0,0
1,26,Male,0,0,0,0,1,1,4,272,...,47,134,115,0,0,7,0,174527,0,0
2,78,Male,0,0,1,0,0,1,6,268,...,54,104,117,0,1,10,1,1760112,1,0
3,58,Male,1,0,1,0,0,1,9,224,...,79,91,65,0,0,1,1,1398213,0,0
4,22,Male,0,0,0,0,0,1,5,277,...,23,141,109,0,0,9,0,97987,0,1

In [11]:
data.drop(['Annual_Income','Health_Insurance','Healthcare_Access','Air_Pollution_Exposure'],axis=1,inplace=True)

In [12]:
data.head()

,Age,Gender,Diabetes,Hypertension,Obesity,Smoking,Alcohol_Consumption,Physical_Activity,Diet_Score,Cholesterol_Level,Triglyceride_Level,LDL_Level,HDL_Level,Systolic_BP,Diastolic_BP,Family_History,Stress_Level,Heart_Attack_Risk
0,42,Female,0,0,1,1,0,0,9,248,125,93,42,93,119,0,4,0
1,26,Male,0,0,0,0,1,1,4,272,51,153,47,134,115,0,7,0
2,78,Male,0,0,1,0,0,1,6,268,213,130,54,104,117,1,10,0
3,58,Male,1,0,1,0,0,1,9,224,250,130,79,91,65,0,1,0
4,22,Male,0,0,0,0,0,1,5,277,129,150,23,141,109,0,9,1

In [13]:
data['Gender']=data['Gender'].map({'Male':1,'Female':0})

In [14]:
X=data.drop('Heart_Attack_Risk',axis=1)
y=data['Heart_Attack_Risk']

In [15]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.20,random_state=42)

In [16]:
scaler=StandardScaler()

In [17]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [18]:
liner_model=LinearRegression()

In [19]:
liner_model.fit(X_train,y_train)

LinearRegression()

In [20]:
y_pred_LinReg=liner_model.predict(X_test)

In [21]:
y_pred_LinReg

array([0.31752998, 0.29247306, 0.30756163, ..., 0.31086557, 0.31228915,
       0.31165069])

In [22]:
logistic_model=LogisticRegression()

In [23]:
logistic_model.fit(X_train_scaled,y_train)

LogisticRegression()

In [24]:
y_pred_logstc=logistic_model.predict(X_test_scaled)

In [25]:
y_pred_logstc

array([0, 0, 0, ..., 0, 0, 0])

In [26]:
confusion_matrix(y_pred_logstc,y_test)

array([[1411,  589],
       [   0,    0]])

In [27]:
print(classification_report(y_pred_logstc,y_test))

              precision    recall  f1-score   support

           0       1.00      0.71      0.83      2000
           1       0.00      0.00      0.00         0

    accuracy                           0.71      2000
   macro avg       0.50      0.35      0.41      2000
weighted avg       1.00      0.71      0.83      2000

In [28]:
model_knn=KNeighborsClassifier(n_neighbors=5)

In [29]:
model_knn.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [30]:
y_pred_knn=model_knn.predict(X_test_scaled)

In [31]:
print(classification_report(y_pred_knn,y_test))

              precision    recall  f1-score   support

           0       0.84      0.70      0.76      1681
           1       0.15      0.28      0.19       319

    accuracy                           0.63      2000
   macro avg       0.49      0.49      0.48      2000
weighted avg       0.73      0.63      0.67      2000

In [32]:
model_nb=GaussianNB()

In [33]:
model_nb.fit(X_train_scaled,y_train)

GaussianNB()

In [34]:
y_pred_nb=model_nb.predict(X_test_scaled)

In [35]:
print(classification_report(y_pred_nb,y_test))

              precision    recall  f1-score   support

           0       1.00      0.71      0.83      2000
           1       0.00      0.00      0.00         0

    accuracy                           0.71      2000
   macro avg       0.50      0.35      0.41      2000
weighted avg       1.00      0.71      0.83      2000

In [36]:
model_svc=SVC(kernel='rbf')

In [37]:
model_svc.fit(X_train_scaled,y_train)

SVC()

In [38]:
y_pred_svm=model_svc.predict(X_test_scaled)

In [39]:
print(classification_report(y_pred_svm,y_test))

              precision    recall  f1-score   support

           0       1.00      0.71      0.83      2000
           1       0.00      0.00      0.00         0

    accuracy                           0.71      2000
   macro avg       0.50      0.35      0.41      2000
weighted avg       1.00      0.71      0.83      2000

In [40]:
model_dt=DecisionTreeClassifier()

In [41]:
model_dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [42]:
y_pred_dt=model_dt.predict(X_test)

In [43]:
print(classification_report(y_pred_dt,y_test))

              precision    recall  f1-score   support

           0       0.71      0.73      0.72      1376
           1       0.36      0.34      0.35       624

    accuracy                           0.61      2000
   macro avg       0.54      0.53      0.53      2000
weighted avg       0.60      0.61      0.60      2000

In [52]:
from sklearn.model_selection import cross_val_score

In [53]:
X=data.drop('Heart_Attack_Risk',axis=1)
y=data['Heart_Attack_Risk']

In [54]:
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

In [55]:
score=cross_val_score(model_svc,X_scaled,y,cv=5,scoring='accuracy')

In [57]:
score

array([0.6995, 0.6995, 0.6995, 0.699 , 0.699 ])

In [58]:
score.mean()

np.float64(0.6992999999999999)